spring:
  datasource:
    url: jdbc:postgresql://tcp-mo5.mogenius.io:41398/covid-db
    username: postgre
    password: {POSTGRES_PASSWORD}
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql : true
      hibernate.ddl-auto: create-drop