server:
  port: 9797
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/covid-db
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PSWD}
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql : true
      hibernate.ddl-auto: create-drop