spring:
  datasource:
    url: jdbc:postgresql://dbapi-kcslp0:5432/covid-db
    username: {POSTGRES_USER}
    password: {POSTGRES_PASSWORD}
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql : true
      hibernate.ddl-auto: create-drop